# Generated by Django 4.2.13 on 2024-07-07 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openAiChat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmt_created', models.DateTimeField(auto_now_add=True)),
                ('gmt_modified', models.DateTimeField(auto_now=True)),
                ('userId', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('chat', models.TextField()),
            ],
        ),
    ]
