name: Deployment aliyun server

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ secrets.HOST }} || ${{ secrets.PASSWORD }}"
      - uses: actions/checkout@v4
      - name: run server
        uses: arthurvanl/action-exec-ssh@v1
        with:
          host: ${{ secrets.HOST }}
          username: admin
          password: ${{ secrets.PASSWORD }}
          commands: './script/deploymentDpdAi.sh start'