name: Deployment aliyun server

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  aliyun-deployment:
    runs-on: ubuntu-latest
    environment: aliyun-deployment
    steps:
      - name: Check install ssh
        run: |
          apt list --installed | grep openssh-server
      - name: Check code
        uses: actions/checkout@v4
      - name: Create ssh
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.PRIVATE_SECRET_KEY }}" > ~/.ssh/github-actions
          chmod 600 ~/.ssh/id_rsa
          echo -e "Host remote-server\n\tHostName ${{ secrets.HOST }}\n\tUser ${{ secrets.USER }}\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
      - name: Exec script
        run: |
          ssh remote-server './script/deploymentDpdAi.sh restart'
